//! Height field error diagnostic mapping.

use super::*;

impl NodeGeometryDiagnostic {
    pub(super) fn from_height_field_error(
        node_id: u32,
        piece_kind: RoadSurfaceVisualNodePieceKind,
        error: &NodeHeightFieldError,
    ) -> Self {
        let kind = match error {
            NodeHeightFieldError::InputOwnershipMismatch { .. } => {
                NodeGeometryDiagnosticKind::HeightFieldFailure {
                    reason: "input_ownership_mismatch",
                    mouth_order_index: None,
                    band_index: None,
                    kind: None,
                    source_kind: None,
                    height_field_id: None,
                    owner: None,
                    point_x_key: None,
                    point_z_key: None,
                    point_x_mm: None,
                    point_z_mm: None,
                    axis: None,
                    raw_parameter: None,
                }
            }
            NodeHeightFieldError::DuplicateSourceBand {
                mouth_order_index,
                band_index,
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "duplicate_source_band",
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: None,
                source_kind: None,
                height_field_id: None,
                owner: None,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::MissingRegionBandIndex {
                mouth_order_index,
                kind,
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "missing_region_band_index",
                mouth_order_index: Some(*mouth_order_index),
                band_index: None,
                kind: Some(*kind),
                source_kind: None,
                height_field_id: None,
                owner: None,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::MissingSourceBand {
                mouth_order_index,
                band_index,
                kind,
                owner,
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "missing_source_band",
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: Some(*kind),
                source_kind: Some(*kind),
                height_field_id: None,
                owner: *owner,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::SourceBandKindMismatch {
                mouth_order_index,
                band_index,
                region_kind,
                source_kind,
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "source_band_kind_mismatch",
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: Some(*region_kind),
                source_kind: Some(*source_kind),
                height_field_id: None,
                owner: None,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::RailHeightCarrierGeneration { reason } => {
                NodeGeometryDiagnosticKind::HeightFieldFailure {
                    reason,
                    mouth_order_index: None,
                    band_index: None,
                    kind: None,
                    source_kind: None,
                    height_field_id: None,
                    owner: None,
                    point_x_key: None,
                    point_z_key: None,
                    point_x_mm: None,
                    point_z_mm: None,
                    axis: None,
                    raw_parameter: None,
                }
            }
            NodeHeightFieldError::InvalidSourceBandHeightCarrier {
                mouth_order_index,
                band_index,
                source_kind,
                height_field_id,
                reason,
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason,
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: None,
                source_kind: Some(*source_kind),
                height_field_id: Some(*height_field_id),
                owner: None,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::MissingGeneratedContourHeightPoints {
                mouth_order_index,
                band_index,
                source_kind,
                height_field_id,
                ..
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "missing_generated_contour_height_points",
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: None,
                source_kind: Some(*source_kind),
                height_field_id: Some(*height_field_id),
                owner: None,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::GeneratedContourMissingSourceBandIndex {
                mouth_order_index,
                source_kind,
                ..
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "generated_contour_missing_source_band_index",
                mouth_order_index: Some(*mouth_order_index),
                band_index: None,
                kind: None,
                source_kind: Some(*source_kind),
                height_field_id: None,
                owner: None,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::GeneratedContourMissingSourceBand {
                mouth_order_index,
                band_index,
                source_kind,
                owner,
                ..
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "generated_contour_source_band_missing",
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: None,
                source_kind: Some(*source_kind),
                height_field_id: None,
                owner: *owner,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::InvalidHeightCarrierContour {
                mouth_order_index,
                band_index,
                source_kind,
                height_field_id,
                reason,
                ..
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason,
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: None,
                source_kind: Some(*source_kind),
                height_field_id: Some(*height_field_id),
                owner: None,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: None,
                point_z_mm: None,
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::VertexOutsideHeightField {
                mouth_order_index,
                band_index,
                source_kind,
                height_field_id,
                owner,
                point_x_mm,
                point_z_mm,
                axis,
                raw_parameter,
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "vertex_outside_height_field",
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: None,
                source_kind: Some(*source_kind),
                height_field_id: Some(*height_field_id),
                owner: *owner,
                point_x_key: None,
                point_z_key: None,
                point_x_mm: Some(*point_x_mm),
                point_z_mm: Some(*point_z_mm),
                axis: Some(*axis),
                raw_parameter: Some(*raw_parameter),
            },
            NodeHeightFieldError::MissingOwnedRegionCarrierSupport {
                mouth_order_index,
                band_index,
                source_kind,
                height_field_id,
                owner,
                point_x_key,
                point_z_key,
                point_x_mm,
                point_z_mm,
            } => NodeGeometryDiagnosticKind::HeightFieldFailure {
                reason: "missing_owned_region_carrier_support",
                mouth_order_index: Some(*mouth_order_index),
                band_index: Some(*band_index),
                kind: None,
                source_kind: Some(*source_kind),
                height_field_id: Some(*height_field_id),
                owner: Some(*owner),
                point_x_key: Some(*point_x_key),
                point_z_key: Some(*point_z_key),
                point_x_mm: Some(*point_x_mm),
                point_z_mm: Some(*point_z_mm),
                axis: None,
                raw_parameter: None,
            },
            NodeHeightFieldError::MissingCarrierProvenanceHeight {
                mouth_order_index,
                band_index,
                source_kind,
                height_field_id,
                point_x_key,
                point_z_key,
                point_x_mm,
                point_z_mm,
                source_segment_id,
            } => NodeGeometryDiagnosticKind::MissingCarrierProvenanceHeight {
                point_x_key: *point_x_key,
                point_z_key: *point_z_key,
                point_x_mm: *point_x_mm,
                point_z_mm: *point_z_mm,
                source_kind: *source_kind,
                source_mouth_order_index: *mouth_order_index,
                source_band_index: *band_index,
                height_field_id: *height_field_id,
                source_segment_id: *source_segment_id,
            },
            NodeHeightFieldError::TerminalCapGeneration { error } => {
                NodeGeometryDiagnosticKind::HeightFieldFailure {
                    reason: error.reason.diagnostic_reason(),
                    mouth_order_index: Some(error.mouth_order_index),
                    band_index: error.source_band_index,
                    kind: error.band_kind,
                    source_kind: error.band_kind,
                    height_field_id: None,
                    owner: None,
                    point_x_key: None,
                    point_z_key: None,
                    point_x_mm: None,
                    point_z_mm: None,
                    axis: None,
                    raw_parameter: None,
                }
            }
            NodeHeightFieldError::SourceHeightFieldConflict {
                mouth_order_index,
                band_index,
                source_kind,
                height_field_id,
                owner,
                existing_authority,
                incoming_authority,
                point_x_mm,
                point_z_mm,
                existing_height_mm,
                incoming_height_mm,
            } => NodeGeometryDiagnosticKind::SourceHeightFieldConflict {
                mouth_order_index: *mouth_order_index,
                band_index: *band_index,
                source_kind: *source_kind,
                height_field_id: *height_field_id,
                owner: *owner,
                existing_authority: *existing_authority,
                incoming_authority: *incoming_authority,
                x_mm: *point_x_mm,
                z_mm: *point_z_mm,
                existing_height_mm: *existing_height_mm,
                incoming_height_mm: *incoming_height_mm,
            },
            NodeHeightFieldError::SharedSourceHeightConflict {
                point_x_mm,
                point_z_mm,
                kind,
                owner,
                opposite_owner,
                height_field_id,
                incoming_owner,
                incoming_height_field_id,
                constraint_index,
                existing_authority,
                incoming_authority,
                existing_height_mm,
                incoming_height_mm,
            } => NodeGeometryDiagnosticKind::SharedSourceHeightConflict {
                x_mm: *point_x_mm,
                z_mm: *point_z_mm,
                kind: *kind,
                owner: *owner,
                opposite_owner: *opposite_owner,
                height_field_id: *height_field_id,
                incoming_owner: *incoming_owner,
                incoming_height_field_id: *incoming_height_field_id,
                constraint_index: *constraint_index,
                existing_authority: *existing_authority,
                incoming_authority: *incoming_authority,
                existing_height_mm: *existing_height_mm,
                incoming_height_mm: *incoming_height_mm,
                constraint_context: None,
            },
        };
        Self {
            node_id,
            piece_kind,
            stage: NodeGeometryStage::HeightEvaluation,
            backend: NodeGeometryBackend::HeightCarrier,
            kind,
        }
    }
}
