// SPDX-License-Identifier: GPL-2.0-only

//! Network rendering infrastructure for generating road and junction meshes.

mod ownership;
pub mod road;
pub mod test_road_mesh;
use super::graph::RegionGraph;
use super::surface::SurfaceChunkKey;
use godot::prelude::*;
pub(crate) use ownership::NetworkMeshOwner;
use ownership::OwnedVertexRange;
use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

#[derive(Debug)]
struct NetworkMeshChunkPartition {
    chunk_span_m: f32,
    chunk_origin_x_m: f32,
    chunk_origin_z_m: f32,
    target_chunks: BTreeSet<SurfaceChunkKey>,
    chunks: BTreeMap<SurfaceChunkKey, NetworkMeshData>,
}

/// Container for all mesh data generated by a transit renderer.
///
/// Includes vertices, normals, UVs, and colors for multiple visual layers.
#[derive(Debug)]
pub struct NetworkMeshData {
    /// Vertices for the road-owned earthwork layer.
    pub earthwork_vertices: Vec<Vector3>,
    /// Normals for the earthwork layer.
    pub earthwork_normals: Vec<Vector3>,
    /// UV coordinates for the earthwork layer.
    pub earthwork_uvs: Vec<Vector2>,
    /// Vertex colors for the earthwork layer.
    pub earthwork_colors: Vec<Color>,
    /// Vertices for the curb / shoulder transition layer.
    pub curb_vertices: Vec<Vector3>,
    /// Normals for the curb / shoulder transition layer.
    pub curb_normals: Vec<Vector3>,
    /// UV coordinates for the curb / shoulder transition layer.
    pub curb_uvs: Vec<Vector2>,
    /// Vertex colors for the curb / shoulder transition layer.
    pub curb_colors: Vec<Color>,
    /// Vertices for raised-step faces between solved owner-pair top surfaces.
    pub raised_step_vertices: Vec<Vector3>,
    /// Normals for raised-step faces.
    pub raised_step_normals: Vec<Vector3>,
    /// UV coordinates for raised-step faces.
    pub raised_step_uvs: Vec<Vector2>,
    /// Vertex colors for raised-step faces.
    pub raised_step_colors: Vec<Color>,
    /// Vertices for the sidewalk layer.
    pub sidewalk_vertices: Vec<Vector3>,
    /// Normals for the sidewalk layer.
    pub sidewalk_normals: Vec<Vector3>,
    /// UV coordinates for the sidewalk layer.
    pub sidewalk_uvs: Vec<Vector2>,
    /// Vertex colors for the sidewalk layer.
    pub sidewalk_colors: Vec<Color>,
    /// Vertices for the asphalt road surface.
    pub road_vertices: Vec<Vector3>,
    /// Normals for the road surface.
    pub road_normals: Vec<Vector3>,
    /// UV coordinates for the road surface.
    pub road_uvs: Vec<Vector2>,
    /// Vertex colors for the road surface.
    pub road_colors: Vec<Color>,
    /// Vertices for lane markings and paint.
    pub marking_vertices: Vec<Vector3>,
    /// Normals for lane markings.
    pub marking_normals: Vec<Vector3>,
    /// UV coordinates for lane markings.
    pub marking_uvs: Vec<Vector2>,
    /// Vertex colors for lane markings.
    pub marking_colors: Vec<Color>,
    /// Vertices for bridge decks, walls, and tunnel portals.
    pub concrete_vertices: Vec<Vector3>,
    /// Normals for structural concrete.
    pub concrete_normals: Vec<Vector3>,
    /// UV coordinates for structural concrete.
    pub concrete_uvs: Vec<Vector2>,
    /// Vertex colors for structural concrete.
    pub concrete_colors: Vec<Color>,
    // Source ranges extend the existing chunk cache; previews can replace owners without
    // clipping triangles heuristically or rebuilding unrelated roads in the same chunk.
    current_owner: Option<NetworkMeshOwner>,
    owner_ranges: [Vec<OwnedVertexRange>; 7],
    chunk_partition: Option<NetworkMeshChunkPartition>,
    // Set only by `seal`: the type is not `Clone`, so the certified buffers cannot change
    // once shared behind the returned `Arc`.
    render_payload_validated: bool,
}

impl NetworkMeshData {
    /// Creates a new, empty network mesh data container.
    pub fn new() -> Self {
        Self {
            earthwork_vertices: Vec::new(),
            earthwork_normals: Vec::new(),
            earthwork_uvs: Vec::new(),
            earthwork_colors: Vec::new(),
            curb_vertices: Vec::new(),
            curb_normals: Vec::new(),
            curb_uvs: Vec::new(),
            curb_colors: Vec::new(),
            raised_step_vertices: Vec::new(),
            raised_step_normals: Vec::new(),
            raised_step_uvs: Vec::new(),
            raised_step_colors: Vec::new(),
            sidewalk_vertices: Vec::new(),
            sidewalk_normals: Vec::new(),
            sidewalk_uvs: Vec::new(),
            sidewalk_colors: Vec::new(),
            road_vertices: Vec::new(),
            road_normals: Vec::new(),
            road_uvs: Vec::new(),
            road_colors: Vec::new(),
            marking_vertices: Vec::new(),
            marking_normals: Vec::new(),
            marking_uvs: Vec::new(),
            marking_colors: Vec::new(),
            concrete_vertices: Vec::new(),
            concrete_normals: Vec::new(),
            concrete_uvs: Vec::new(),
            concrete_colors: Vec::new(),
            current_owner: None,
            owner_ranges: Default::default(),
            chunk_partition: None,
            render_payload_validated: false,
        }
    }

    /// Creates a triangle sink that routes geometry into the requested render chunks.
    pub(crate) fn new_chunk_partitioned(
        chunk_span_m: f32,
        chunk_origin_x_m: f32,
        chunk_origin_z_m: f32,
        target_chunks: BTreeSet<SurfaceChunkKey>,
    ) -> Self {
        let mut mesh = Self::new();
        mesh.chunk_partition = Some(NetworkMeshChunkPartition {
            chunk_span_m: chunk_span_m.max(f32::EPSILON),
            chunk_origin_x_m,
            chunk_origin_z_m,
            target_chunks,
            chunks: BTreeMap::new(),
        });
        mesh
    }

    /// Consumes a partitioning sink and returns its non-empty chunk-local meshes.
    pub(crate) fn into_partitioned_chunks(mut self) -> BTreeMap<SurfaceChunkKey, NetworkMeshData> {
        self.chunk_partition
            .take()
            .map(|partition| partition.chunks)
            .unwrap_or_default()
    }

    /// Reports whether every material layer is empty.
    pub(crate) fn is_empty(&self) -> bool {
        self.earthwork_vertices.is_empty()
            && self.curb_vertices.is_empty()
            && self.raised_step_vertices.is_empty()
            && self.sidewalk_vertices.is_empty()
            && self.road_vertices.is_empty()
            && self.marking_vertices.is_empty()
            && self.concrete_vertices.is_empty()
    }

    /// Validates the final render buffers once and freezes them for publication.
    ///
    /// Every layer must hold whole triangles with matching attribute counts and finite
    /// components. The certificate travels with these exact immutable buffers so the Godot
    /// boundary can skip its per-vertex scan. O(vertices); run it on the producing thread.
    pub(crate) fn seal(mut self) -> Arc<Self> {
        self.render_payload_validated = self.render_payload_is_valid();
        Arc::new(self)
    }

    /// Reports whether `seal` certified these buffers; uncertified meshes need full validation.
    pub(crate) fn render_payload_validated(&self) -> bool {
        self.render_payload_validated
    }

    fn render_payload_is_valid(&self) -> bool {
        fn layer_valid(
            vertices: &[Vector3],
            normals: &[Vector3],
            uvs: &[Vector2],
            colors: &[Color],
        ) -> bool {
            let finite3 = |v: &Vector3| v.x.is_finite() && v.y.is_finite() && v.z.is_finite();
            vertices.len().is_multiple_of(3)
                && normals.len() == vertices.len()
                && uvs.len() == vertices.len()
                && colors.len() == vertices.len()
                && vertices.iter().all(finite3)
                && normals.iter().all(finite3)
                && uvs.iter().all(|uv| uv.x.is_finite() && uv.y.is_finite())
                && colors.iter().all(|c| {
                    c.r.is_finite() && c.g.is_finite() && c.b.is_finite() && c.a.is_finite()
                })
        }
        [
            (
                &self.earthwork_vertices,
                &self.earthwork_normals,
                &self.earthwork_uvs,
                &self.earthwork_colors,
            ),
            (
                &self.curb_vertices,
                &self.curb_normals,
                &self.curb_uvs,
                &self.curb_colors,
            ),
            (
                &self.raised_step_vertices,
                &self.raised_step_normals,
                &self.raised_step_uvs,
                &self.raised_step_colors,
            ),
            (
                &self.sidewalk_vertices,
                &self.sidewalk_normals,
                &self.sidewalk_uvs,
                &self.sidewalk_colors,
            ),
            (
                &self.road_vertices,
                &self.road_normals,
                &self.road_uvs,
                &self.road_colors,
            ),
            (
                &self.marking_vertices,
                &self.marking_normals,
                &self.marking_uvs,
                &self.marking_colors,
            ),
            (
                &self.concrete_vertices,
                &self.concrete_normals,
                &self.concrete_uvs,
                &self.concrete_colors,
            ),
        ]
        .into_iter()
        .all(|(vertices, normals, uvs, colors)| layer_valid(vertices, normals, uvs, colors))
    }

    /// Returns the total number of non-indexed vertices across all material layers.
    pub(crate) fn vertex_count(&self) -> usize {
        self.earthwork_vertices.len()
            + self.curb_vertices.len()
            + self.raised_step_vertices.len()
            + self.sidewalk_vertices.len()
            + self.road_vertices.len()
            + self.marking_vertices.len()
            + self.concrete_vertices.len()
    }
}

/// Trait for generating mesh data from the road network graph.
pub trait TransitRenderer {
    /// Generates visual mesh data for the given graph and lane system.
    fn generate_mesh_data(
        &self,
        graph: &RegionGraph,
        lane_system: &crate::simulation::network::lanes::LaneSystem,
        terrain: &crate::simulation::terrain::TerrainSystem,
    ) -> NetworkMeshData;
}

#[cfg(test)]
mod tests {
    use super::*;

    fn triangle() -> NetworkMeshData {
        let mut mesh = NetworkMeshData::new();
        mesh.road_vertices = vec![Vector3::ZERO, Vector3::RIGHT, Vector3::BACK];
        mesh.road_normals = vec![Vector3::UP; 3];
        mesh.road_uvs = vec![Vector2::ZERO; 3];
        mesh.road_colors = vec![Color::WHITE; 3];
        mesh
    }

    #[test]
    fn seal_certifies_only_well_formed_finite_buffers() {
        assert!(!triangle().render_payload_validated());
        assert!(triangle().seal().render_payload_validated());
        assert!(NetworkMeshData::new().seal().render_payload_validated());

        let malformed: [fn(&mut NetworkMeshData); 6] = [
            |mesh| mesh.road_vertices[1].y = f32::NAN,
            |mesh| mesh.road_normals[0].z = f32::INFINITY,
            |mesh| mesh.road_uvs[2].x = f32::NEG_INFINITY,
            |mesh| mesh.road_colors[0].a = f32::NAN,
            |mesh| {
                mesh.road_colors.pop();
            },
            |mesh| {
                mesh.marking_vertices.push(Vector3::ZERO);
                mesh.marking_normals.push(Vector3::UP);
                mesh.marking_uvs.push(Vector2::ZERO);
                mesh.marking_colors.push(Color::WHITE);
            },
        ];
        for corrupt in malformed {
            let mut mesh = triangle();
            corrupt(&mut mesh);
            assert!(!mesh.seal().render_payload_validated());
        }
    }
}
