//! Network rendering infrastructure for generating road and junction meshes.

pub mod road;
pub mod test_road_mesh;
use super::graph::RegionGraph;
use godot::prelude::*;

/// Container for all mesh data generated by a transit renderer.
///
/// Includes vertices, normals, UVs, and colors for multiple visual layers.
pub struct NetworkMeshData {
    /// Vertices for the road-owned earthwork layer.
    pub earthwork_vertices: Vec<Vector3>,
    /// Normals for the earthwork layer.
    pub earthwork_normals: Vec<Vector3>,
    /// UV coordinates for the earthwork layer.
    pub earthwork_uvs: Vec<Vector2>,
    /// Vertex colors for the earthwork layer.
    pub earthwork_colors: Vec<Color>,
    /// Vertices for the sidewalk/curb layer.
    pub sidewalk_vertices: Vec<Vector3>,
    /// Normals for the sidewalk layer.
    pub sidewalk_normals: Vec<Vector3>,
    /// UV coordinates for the sidewalk layer.
    pub sidewalk_uvs: Vec<Vector2>,
    /// Vertex colors for the sidewalk layer.
    pub sidewalk_colors: Vec<Color>,
    /// Vertices for the asphalt road surface.
    pub road_vertices: Vec<Vector3>,
    /// Normals for the road surface.
    pub road_normals: Vec<Vector3>,
    /// UV coordinates for the road surface.
    pub road_uvs: Vec<Vector2>,
    /// Vertex colors for the road surface.
    pub road_colors: Vec<Color>,
    /// Vertices for lane markings and paint.
    pub marking_vertices: Vec<Vector3>,
    /// Normals for lane markings.
    pub marking_normals: Vec<Vector3>,
    /// UV coordinates for lane markings.
    pub marking_uvs: Vec<Vector2>,
    /// Vertex colors for lane markings.
    pub marking_colors: Vec<Color>,
    /// Vertices for bridge decks, walls, and tunnel portals.
    pub concrete_vertices: Vec<Vector3>,
    /// Normals for structural concrete.
    pub concrete_normals: Vec<Vector3>,
    /// UV coordinates for structural concrete.
    pub concrete_uvs: Vec<Vector2>,
    /// Vertex colors for structural concrete.
    pub concrete_colors: Vec<Color>,
}

impl NetworkMeshData {
    /// Creates a new, empty network mesh data container.
    pub fn new() -> Self {
        Self {
            earthwork_vertices: Vec::new(),
            earthwork_normals: Vec::new(),
            earthwork_uvs: Vec::new(),
            earthwork_colors: Vec::new(),
            sidewalk_vertices: Vec::new(),
            sidewalk_normals: Vec::new(),
            sidewalk_uvs: Vec::new(),
            sidewalk_colors: Vec::new(),
            road_vertices: Vec::new(),
            road_normals: Vec::new(),
            road_uvs: Vec::new(),
            road_colors: Vec::new(),
            marking_vertices: Vec::new(),
            marking_normals: Vec::new(),
            marking_uvs: Vec::new(),
            marking_colors: Vec::new(),
            concrete_vertices: Vec::new(),
            concrete_normals: Vec::new(),
            concrete_uvs: Vec::new(),
            concrete_colors: Vec::new(),
        }
    }
}

/// Trait for generating mesh data from the road network graph.
pub trait TransitRenderer {
    /// Generates visual mesh data for the given graph and lane system.
    fn generate_mesh_data(
        &self,
        graph: &RegionGraph,
        lane_system: &crate::simulation::network::lanes::LaneSystem,
        terrain: &crate::simulation::terrain::TerrainSystem,
    ) -> NetworkMeshData;
}
