// SPDX-License-Identifier: GPL-2.0-only

//! Network rendering infrastructure for generating road and junction meshes.

pub mod road;
pub mod test_road_mesh;
use super::graph::RegionGraph;
use super::surface::SurfaceChunkKey;
use godot::prelude::*;
use std::collections::{BTreeMap, BTreeSet};

struct NetworkMeshChunkPartition {
    chunk_span_m: f32,
    chunk_origin_x_m: f32,
    chunk_origin_z_m: f32,
    target_chunks: BTreeSet<SurfaceChunkKey>,
    chunks: BTreeMap<SurfaceChunkKey, NetworkMeshData>,
}

/// Container for all mesh data generated by a transit renderer.
///
/// Includes vertices, normals, UVs, and colors for multiple visual layers.
pub struct NetworkMeshData {
    /// Vertices for the road-owned earthwork layer.
    pub earthwork_vertices: Vec<Vector3>,
    /// Normals for the earthwork layer.
    pub earthwork_normals: Vec<Vector3>,
    /// UV coordinates for the earthwork layer.
    pub earthwork_uvs: Vec<Vector2>,
    /// Vertex colors for the earthwork layer.
    pub earthwork_colors: Vec<Color>,
    /// Vertices for the curb / shoulder transition layer.
    pub curb_vertices: Vec<Vector3>,
    /// Normals for the curb / shoulder transition layer.
    pub curb_normals: Vec<Vector3>,
    /// UV coordinates for the curb / shoulder transition layer.
    pub curb_uvs: Vec<Vector2>,
    /// Vertex colors for the curb / shoulder transition layer.
    pub curb_colors: Vec<Color>,
    /// Vertices for raised-step faces between solved owner-pair top surfaces.
    pub raised_step_vertices: Vec<Vector3>,
    /// Normals for raised-step faces.
    pub raised_step_normals: Vec<Vector3>,
    /// UV coordinates for raised-step faces.
    pub raised_step_uvs: Vec<Vector2>,
    /// Vertex colors for raised-step faces.
    pub raised_step_colors: Vec<Color>,
    /// Vertices for the sidewalk layer.
    pub sidewalk_vertices: Vec<Vector3>,
    /// Normals for the sidewalk layer.
    pub sidewalk_normals: Vec<Vector3>,
    /// UV coordinates for the sidewalk layer.
    pub sidewalk_uvs: Vec<Vector2>,
    /// Vertex colors for the sidewalk layer.
    pub sidewalk_colors: Vec<Color>,
    /// Vertices for the asphalt road surface.
    pub road_vertices: Vec<Vector3>,
    /// Normals for the road surface.
    pub road_normals: Vec<Vector3>,
    /// UV coordinates for the road surface.
    pub road_uvs: Vec<Vector2>,
    /// Vertex colors for the road surface.
    pub road_colors: Vec<Color>,
    /// Vertices for lane markings and paint.
    pub marking_vertices: Vec<Vector3>,
    /// Normals for lane markings.
    pub marking_normals: Vec<Vector3>,
    /// UV coordinates for lane markings.
    pub marking_uvs: Vec<Vector2>,
    /// Vertex colors for lane markings.
    pub marking_colors: Vec<Color>,
    /// Vertices for bridge decks, walls, and tunnel portals.
    pub concrete_vertices: Vec<Vector3>,
    /// Normals for structural concrete.
    pub concrete_normals: Vec<Vector3>,
    /// UV coordinates for structural concrete.
    pub concrete_uvs: Vec<Vector2>,
    /// Vertex colors for structural concrete.
    pub concrete_colors: Vec<Color>,
    chunk_partition: Option<NetworkMeshChunkPartition>,
}

impl NetworkMeshData {
    /// Creates a new, empty network mesh data container.
    pub fn new() -> Self {
        Self {
            earthwork_vertices: Vec::new(),
            earthwork_normals: Vec::new(),
            earthwork_uvs: Vec::new(),
            earthwork_colors: Vec::new(),
            curb_vertices: Vec::new(),
            curb_normals: Vec::new(),
            curb_uvs: Vec::new(),
            curb_colors: Vec::new(),
            raised_step_vertices: Vec::new(),
            raised_step_normals: Vec::new(),
            raised_step_uvs: Vec::new(),
            raised_step_colors: Vec::new(),
            sidewalk_vertices: Vec::new(),
            sidewalk_normals: Vec::new(),
            sidewalk_uvs: Vec::new(),
            sidewalk_colors: Vec::new(),
            road_vertices: Vec::new(),
            road_normals: Vec::new(),
            road_uvs: Vec::new(),
            road_colors: Vec::new(),
            marking_vertices: Vec::new(),
            marking_normals: Vec::new(),
            marking_uvs: Vec::new(),
            marking_colors: Vec::new(),
            concrete_vertices: Vec::new(),
            concrete_normals: Vec::new(),
            concrete_uvs: Vec::new(),
            concrete_colors: Vec::new(),
            chunk_partition: None,
        }
    }

    /// Creates a triangle sink that routes geometry into the requested render chunks.
    pub(crate) fn new_chunk_partitioned(
        chunk_span_m: f32,
        chunk_origin_x_m: f32,
        chunk_origin_z_m: f32,
        target_chunks: BTreeSet<SurfaceChunkKey>,
    ) -> Self {
        let mut mesh = Self::new();
        mesh.chunk_partition = Some(NetworkMeshChunkPartition {
            chunk_span_m: chunk_span_m.max(f32::EPSILON),
            chunk_origin_x_m,
            chunk_origin_z_m,
            target_chunks,
            chunks: BTreeMap::new(),
        });
        mesh
    }

    /// Consumes a partitioning sink and returns its non-empty chunk-local meshes.
    pub(crate) fn into_partitioned_chunks(mut self) -> BTreeMap<SurfaceChunkKey, NetworkMeshData> {
        self.chunk_partition
            .take()
            .map(|partition| partition.chunks)
            .unwrap_or_default()
    }

    /// Reports whether every material layer is empty.
    pub(crate) fn is_empty(&self) -> bool {
        self.earthwork_vertices.is_empty()
            && self.curb_vertices.is_empty()
            && self.raised_step_vertices.is_empty()
            && self.sidewalk_vertices.is_empty()
            && self.road_vertices.is_empty()
            && self.marking_vertices.is_empty()
            && self.concrete_vertices.is_empty()
    }

    /// Returns the total number of non-indexed vertices across all material layers.
    pub(crate) fn vertex_count(&self) -> usize {
        self.earthwork_vertices.len()
            + self.curb_vertices.len()
            + self.raised_step_vertices.len()
            + self.sidewalk_vertices.len()
            + self.road_vertices.len()
            + self.marking_vertices.len()
            + self.concrete_vertices.len()
    }
}

/// Trait for generating mesh data from the road network graph.
pub trait TransitRenderer {
    /// Generates visual mesh data for the given graph and lane system.
    fn generate_mesh_data(
        &self,
        graph: &RegionGraph,
        lane_system: &crate::simulation::network::lanes::LaneSystem,
        terrain: &crate::simulation::terrain::TerrainSystem,
    ) -> NetworkMeshData;
}
